from pydantic import BaseModel, Field, ConfigDict
from decimal import Decimal
from typing import Optional, Any
from app.models.enums import TransactionStatus, TransactionType, PaymentProvider


class PaymentInitiate(BaseModel):
    """What the E-commerce app sends to start a payment"""

    external_order_id: str = Field(..., description="Order ID from E-commerce DB")
    external_customer_id: str = Field(..., description="Customer ID from E-commerce DB")
    amount: Decimal = Field(..., gt=0, decimal_places=2)
    currency: str = Field(default="USD", min_length=3, max_length=3)
    provider: PaymentProvider
    idempotency_key: str = Field(
        ..., description="Unique key generated by E-commerce to prevent double-charge"
    )


class PaymentResponse(BaseModel):
    """What the Gateway returns after talking to Stripe/PayPal"""

    gateway_transaction_id: int
    provider_transaction_id: Optional[str] = None
    client_secret: Optional[str] = (
        None  # The secret used by client-side to confirm payment
    )
    status: TransactionStatus
