"""initial_migration

Revision ID: 93c621f452b9
Revises: 
Create Date: 2026-01-23 00:40:10.336974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c621f452b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_apps',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_apps_api_key'), 'client_apps', ['api_key'], unique=True)
    op.create_index(op.f('ix_client_apps_id'), 'client_apps', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('client_app_id', sa.Integer(), nullable=False),
    sa.Column('external_order_id', sa.String(length=100), nullable=False),
    sa.Column('external_customer_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'INR', 'EUR', name='currency'), nullable=True),
    sa.Column('type', sa.Enum('PAYMENT', 'REFUND', name='transactiontype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=True),
    sa.Column('provider', sa.Enum('STRIPE', 'PAYPAL', 'RAZORPAY', name='paymentprovider'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_apps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_external_customer_id'), 'transactions', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_order_id'), 'transactions', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_provider_transaction_id'), 'transactions', ['provider_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_provider_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_order_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_client_apps_id'), table_name='client_apps')
    op.drop_index(op.f('ix_client_apps_api_key'), table_name='client_apps')
    op.drop_table('client_apps')
    # ### end Alembic commands ###
