from sqlalchemy import Column, String, Integer, Numeric, ForeignKey, Enum, JSON
from sqlalchemy.orm import relationship
from app.models.base import BaseModel
from app.models.enums import (
    TransactionStatus,
    TransactionType,
    PaymentProvider,
    Currency,
)


class Transaction(BaseModel):
    __tablename__ = "transactions"

    # Reference to the internal service that called us
    client_app_id = Column(
        Integer, ForeignKey("client_apps.id", ondelete="RESTRICT"), nullable=False
    )

    # IDs from the E-commerce Database
    external_order_id = Column(String(100), index=True, nullable=False)
    external_customer_id = Column(String(100), index=True, nullable=False)

    # Financial details (Never use Float!)
    amount = Column(Numeric(18, 2), nullable=False)
    currency = Column(Enum(Currency), default=Currency.INR)

    # Gateway specific logic
    type = Column(Enum(TransactionType), default=TransactionType.PAYMENT)
    status = Column(Enum(TransactionStatus), default=TransactionStatus.PENDING)
    provider = Column(Enum(PaymentProvider), nullable=False)

    # Crucial for Retries and Safety
    idempotency_key = Column(String(255), unique=True, index=True, nullable=False)

    # The ID generated by Stripe/PayPal/Razorpay
    provider_transaction_id = Column(
        String(255), unique=True, index=True, nullable=True
    )

    # Store the raw response from the provider for debugging/audit
    provider_metadata = Column(JSON, nullable=True)

    # Relationships
    client = relationship("ClientApp", back_populates="transactions")
